# Generated by Django 6.1 on 2026-08-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель (напр. iPhone 11 Pro)')),
                ('imei_or_serial', models.CharField(max_length=50, unique=True, verbose_name='IMEI / Серійник')),
                ('status', models.CharField(choices=[('in_repair', 'На діагностиці / В ремонті'), ('ready', 'Готовий до продажу'), ('sold', 'Продано')], default='in_repair', max_length=20)),
                ('purchase_price', models.IntegerField(verbose_name='Ціна покупки (грн)')),
            ],
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Що зроблено (напр. UnlockTool, заміна АКБ)')),
                ('cost', models.IntegerField(verbose_name='Витрати на запчастини/софт (грн)')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='inventory.device')),
            ],
        ),
    ]
